import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    /* Generated by `npm run test:browser` — esbuild bundles the harness plus
       React into one file, so linting it reports thousands of problems about
       code nobody here wrote. It is gitignored; this keeps it out of lint too. */
    "tests/browser/bundle.js",
  ]),
]);

export default eslintConfig;
