/*
  tests/pdfs.test.mjs
  --------------------------------------------------------------------------
  PDF validation, the overlay model, and the registry entry.

  The header sniffing is tested against a REAL PDF generated by pdf-lib rather
  than a hand-written byte string, so the assertions are about actual files and
  not about my idea of what a PDF looks like.

  Storage functions that need IndexedDB are absent — the parts worth testing
  (validation, size limits, the edit model, pruning's guard) are all pure and
  are covered here.
  -------------------------------------------------------------------------- */

import { PDFDocument, StandardFonts } from 'pdf-lib'
import {
  sniffPdf, looksEncrypted, newPdfId, formatPdfSize,
  MAX_PDF_BYTES, PDF_EXTS, EDIT_KINDS, makeEdit, editsForPage,
} from '../lib/pdfs.js'
import { BLOCK_TYPES, createBlock, blockHasContent, clonepatch, railFor } from '../components/notebook/blockRegistry.js'

let pass = 0, fail = 0
const ok = (c, m, extra = '') => { c ? (pass++, console.log('  ok   ' + m)) : (fail++, console.log(`  FAIL ${m}${extra ? '\n        ' + extra : ''}`)) }

/* Build a genuine PDF to test against. */
const doc = await PDFDocument.create()
const font = await doc.embedFont(StandardFonts.Helvetica)
const page = doc.addPage([595.28, 841.89])
page.drawText('Acme Quarterly Report', { x: 72, y: 769, size: 24, font })
doc.addPage([842, 595])
const REAL_PDF = await doc.save()

/* ── sniffing ────────────────────────────────────────────────────────── */
console.log('\n sniffPdf — against a real generated document')
{
  const r = sniffPdf(REAL_PDF)
  ok(r.ok, 'accepts a real PDF')
  ok(r.offset === 0, 'finds the header at offset 0')
  ok(/^\d\.\d$/.test(r.version), `reads the version (${r.version})`)
}

console.log('\n sniffPdf — rejection')
{
  const enc = new TextEncoder()
  ok(!sniffPdf(enc.encode('PK\x03\x04 this is a zip')).ok, 'rejects a ZIP')
  ok(!sniffPdf(enc.encode('<html><body>hi</body></html>')).ok, 'rejects HTML')
  ok(!sniffPdf(new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0, 0, 0, 0, 0, 0])).ok, 'rejects a PNG')
  ok(!sniffPdf(null).ok, 'rejects null')
  ok(!sniffPdf(new Uint8Array(0)).ok, 'rejects an empty file')
  ok(!sniffPdf(new Uint8Array([0x25, 0x50])).ok, 'rejects a truncated header')
  ok(sniffPdf(enc.encode('%PDF-1.4\n...')).reason === undefined, 'a minimal valid header passes')

  /* Renaming a .docx to .pdf is the exact case the extension check would miss
     and this one catches — which is why validation is by content. */
  ok(!sniffPdf(enc.encode('PK\x03\x04word/document.xml')).ok, 'rejects a .docx renamed to .pdf')
}

console.log('\n sniffPdf — headers that are legally offset')
{
  /* The spec allows junk before %PDF-, and Acrobat tolerates up to 1024 bytes
     of it. Real files from bad producers do this; refusing them would reject
     documents every other reader opens. */
  const enc = new TextEncoder()
  const padded = new Uint8Array([...enc.encode('#'.repeat(300)), ...REAL_PDF])
  const r = sniffPdf(padded)
  ok(r.ok && r.offset === 300, 'accepts a header 300 bytes in, and reports where')

  const tooFar = new Uint8Array([...enc.encode('#'.repeat(4000)), ...REAL_PDF])
  ok(!sniffPdf(tooFar).ok, 'rejects a header beyond the 1024-byte scan window')
}

console.log('\n looksEncrypted')
ok(looksEncrypted(REAL_PDF) === false, 'a plain document is not flagged')
ok(looksEncrypted(new TextEncoder().encode('junk /Encrypt 5 0 R junk'.padStart(200, ' '))) === true, 'an /Encrypt marker near the tail is flagged')
ok(looksEncrypted(null) === false, 'null does not throw')
ok(looksEncrypted(new Uint8Array(0)) === false, 'empty does not throw')

/* ── sizes ───────────────────────────────────────────────────────────── */
console.log('\n sizes')
ok(MAX_PDF_BYTES === 25 * 1024 * 1024, 'cap is 25MB')
ok(formatPdfSize(0) === '0 KB', 'zero')
ok(formatPdfSize(-1) === '0 KB', 'negative clamps')
ok(formatPdfSize(2048) === '2 KB', 'KB')
ok(formatPdfSize(5 * 1024 * 1024) === '5.0 MB', 'MB with one decimal')
ok(formatPdfSize(REAL_PDF.length).endsWith('KB'), `the real document formats sensibly (${formatPdfSize(REAL_PDF.length)})`)
ok(PDF_EXTS.length === 1 && PDF_EXTS[0] === '.pdf', 'one extension, lowercase with the dot — matching how extOf normalises')

console.log('\n newPdfId')
{
  const ids = new Set(Array.from({ length: 500 }, newPdfId))
  ok(ids.size === 500, '500 ids in a tight loop are all distinct')
  ok([...ids].every(i => i.startsWith('pdf_')), 'all prefixed pdf_')
  ok([...ids].every(i => !i.includes('/')), 'no slashes — teleport addresses are slash-delimited')
}

/* ── the overlay model ───────────────────────────────────────────────── */
console.log('\n overlay edits')
{
  ok(EDIT_KINDS.includes('text') && EDIT_KINDS.includes('whiteout') && EDIT_KINDS.includes('highlight'), 'the stage-2 kinds are declared')

  const e = makeEdit('highlight', 2, { rect: { x: 10, y: 20, w: 100, h: 12 }, color: '#ff0' })
  ok(e.kind === 'highlight' && e.page === 2, 'kind and page recorded')
  ok(typeof e.id === 'string' && e.id.startsWith('edit_'), 'gets an id')
  ok(e.rect.w === 100, 'payload passed through')
  ok(typeof e.createdAt === 'number', 'timestamped, so ordering survives a reload')

  let threw = false
  try { makeEdit('nonsense', 0) } catch { threw = true }
  ok(threw, 'an unknown kind throws at creation rather than being written to storage')

  ok(makeEdit('text', -5).page === 0, 'a negative page clamps to 0')
  ok(makeEdit('text', 2.7).page === 2, 'a fractional page floors')
  ok(makeEdit('text', 'abc').page === 0, 'a non-numeric page becomes 0 rather than NaN')

  const edits = [makeEdit('text', 0), makeEdit('text', 1), makeEdit('ink', 1), makeEdit('text', 2)]
  ok(editsForPage(edits, 1).length === 2, 'filters to one page')
  ok(editsForPage(edits, 9).length === 0, 'a page with no edits returns empty')
  ok(editsForPage(null, 0).length === 0, 'null edits does not throw')
  ok(editsForPage(edits, 1)[0].kind === 'text', 'creation order preserved — later edits paint over earlier ones')
}

/* ── the registry entry ──────────────────────────────────────────────── */
console.log('\n pdf block type')
{
  const def = BLOCK_TYPES.pdf
  ok(!!def, 'registered')
  ok(def.icon === 'block-pdf' && def.label === 'PDF', 'label and icon')
  ok(def.rail === 'pdf', 'declares its own contextual rail')
  ok(def.createOpensPicker === true, 'creating one opens the file picker instead of dropping an empty block')
  ok(def.key === null, 'no single-key shortcut — n/t/k/s/i are taken')

  const b = createBlock('pdf', { id: 'b1', x: 5, y: 6, now: 1 })
  ok(b.type === 'pdf' && b.pdfId === null, 'starts with no document')
  ok(b.pdfPage === 1 && b.pdfFit === 'width', 'sensible default view state')
  ok(b.w === 520 && b.h === 620, 'portrait-ish default size, so an A4 page fits without resizing')

  ok(blockHasContent({ type: 'pdf' }) === false, 'an empty pdf block deletes without a prompt')
  ok(blockHasContent({ type: 'pdf', pdfId: 'pdf_1' }) === true, 'one holding a document asks first')

  /* Sharing the id rather than copying bytes is deliberate: two views of one
     document, and 25MB isn't duplicated. */
  const p = clonepatch({ type: 'pdf', w: 500, h: 600, name: 'Report', pdfId: 'pdf_7', pdfPage: 12, pdfFit: 'page' })
  ok(p.pdfId === 'pdf_7', 'duplicating carries the document id')
  ok(p.pdfPage === 12, 'and the page you were on')
  ok(p.pdfFit === 'page', 'and the fit mode')
  ok(p.name === 'Report (copy)', 'and renames the copy')

  ok(railFor({ type: 'pdf' }) === 'pdf', 'railFor resolves the pdf rail')
  ok(railFor({ type: 'table' }) === 'sheet', '…without disturbing the sheet rail')
  ok(railFor({ type: 'text' }) === null, '…or inventing one for text')

  /* Adding a type must not disturb the ones that already existed.

     Deliberately NOT a count. An exact-length assertion on a set designed to
     grow fails on every legitimate addition, says nothing about correctness,
     and teaches you to bump the number without looking — which is how a real
     regression eventually slips through. (This one has now broken twice for
     exactly that reason.) Assert the invariants instead. */
  for (const t of ['text', 'table', 'kanban', 'section', 'image', 'pdf']) {
    ok(!!BLOCK_TYPES[t], `${t} still registered`)
  }
  const orders = Object.values(BLOCK_TYPES).map(d => d.order)
  ok(new Set(orders).size === orders.length, 'no two types claim the same menu position')
  const keys = Object.values(BLOCK_TYPES).map(d => d.key).filter(Boolean)
  ok(new Set(keys).size === keys.length, 'no two types claim the same shortcut key')
}

console.log('\n provenance')
{
  const extracted = { type: 'table', headers: ['A'], rows: [['1']], name: 'Report p12',
    source: { type: 'pdf', pdfId: 'pdf_9', page: 12, bbox: { x: 1, y: 2, w: 3, h: 4 } } }
  const p = clonepatch(extracted)
  ok(p.source?.pdfId === 'pdf_9', 'duplicating an extracted block keeps its source')
  ok(p.source?.page === 12, 'including the page it came from')
  p.source.page = 99
  ok(extracted.source.page === 12, 'and the copy is a real copy, not a shared reference')

  ok(clonepatch({ type: 'text', content: 'x' }).source === undefined,
     'a block with no provenance does not gain an empty one')

  // Provenance rides on the patch, so it survives block creation unchanged.
  const made = createBlock('table', { id: 'b1', x: 0, y: 0, now: 1, patch: p })
  ok(made.source?.pdfId === 'pdf_9', 'and it survives createBlock')
}

console.log(`\n ${pass} passed, ${fail} failed\n`)
process.exit(fail ? 1 : 0)
